services:
- docker
env:
- dist='ubuntu.bionic'
- dist='ubuntu.xenial'
- dist='raspbian.stretch'
language: go
go: 1.10.x

# skip dependencies
install: true

before_script:
# - if _, err := os.Stat(travis/test); os.IsNotExist(err) { os.Mkdir(travis/test, mode) }
# - import("os" "path/filepath")
# - newpath := filepath.Join(".", "public")
# - os.MkdirAll(newpath, os.ModePerm)
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
script:
- golangci-lint run       # run a bunch of code checkers/linters in parallel
- go test -v -race ./...  # Run all the tests with the race detector enabled
